use_frameworks!

platform :ios, '10.0'

target 'shivalib_Example' do
  pod 'shivalib', :path => '../'
  pod 'TelnyxRTC', '~> 0.1.3'

  target 'shivalib_Tests' do
    inherit! :search_paths

    
  end
end
